name: Manually trigger an Azure Machine Learning job

on:
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: attach workspace
      run: az ml folder attach -w ml-personal -g ml-personal
    - name: run pipeline
      run: az ml run submit-pipeline -n github-manual-trigger -y src/job.yml


