name: Deployment of ML Model

on:
  workflow_dispatch:

jobs:
  create-endpoint:
    runs-on: ubuntu-latest
    environment: 
      name: production
    steps:
    - name: Check out repo Dev
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Create endpoint
      run: az ml online-endpoint create --file src/create-endpoint.yml --workspace-name ml-personal --resource-group ml-personal
    
  deploy-endpoint:
    needs: create-endpoint
    runs-on: ubuntu-latest
    environment: 
      name: production
    steps:
    - name: Check out repo Dev
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Deploy endpoint
      run: az ml online-deployment create --file src/deploy-endpoint.yml --workspace-name ml-personal --resource-group ml-personal --all-traffic



